# Sensing
ray_ground_filter:
  max_clipping_height: 5.0
  min_clipping_height: -0.5
  min_point_distance: 2.9
  res_t_log: false

voxel_grid_filter:
  leaf_size: 2.5
  measurement_range: 200
  res_t_log: false

gnss_calibrator:
  res_t_log: false

# Localization
ndt_matching:
  get_height: true
  ndt_lkas_flag: false
  time_wall: 57
  pnorm_threshold: 0.01
  res_t_log: false
  accuracy_log: false

ndt_config:
  init_x: 57.1
  init_y: 1.38
  init_z: 0.48
  init_roll: 0.0
  init_pitch: 0.0
  init_yaw: 1.57
  resolution: 1.0
  step_size: 0.2
  trans_epsilon: 0.01
  max_iterations: 30

# Detection
lidar_euclidean_cluster_detect:
  clip_min_height: -3.0
  clip_max_height: 4.0
  cluster_size_min: 1
  cluster_size_max: 100000
  res_t_log: false

imm_ukf_pda:
  res_t_log: false

# Planning
op_common_params:
  maxVelocity: 12.0
  maxAcceleration: 10.0
  maxDeceleration: -10.0
  width: 1.85
  length: 4.2

op_global_planner:
  use_static_goal: true
  multilap_flag: false
  res_t_log: false
  use_static_goal: true
  goal_pose_x: 56.3
  goal_pose_y: -15.0
  goal_pose_z: 0.0
  goal_ori_x: 0.0
  goal_ori_y: 0.0
  goal_ori_z: 0.7
  goal_ori_w: 0.7

op_trajectory_generator:
  res_t_log: false

op_motion_predictor:
  prediction_distance: 25.0
  res_t_log: false

op_trajectory_evaluator:
  res_t_log: false

op_behavior_selector:
  ndt_lkas_flag: false
  pnorm_threshold: 0.01
  res_t_log: false

# Control
pure_pursuit:
  lookahead_ratio: 2.0
  minimum_lookahead_distance: 5.0
  res_t_log: false

twist_filter:
  res_t_log: false

twist_gate:
  res_t_log: false

# Safety-Backup
lkas:
  res_t_log: false

twist_combiner:
  ndt_lkas_flag: false
  pnorm_threshold: 0.01